# This is a basic workflow to help you get started with Actions

name: CI

env:
  BINARIES: './output/app_data/jobs/continuous/WebJobForAppManual' # the last folder name will become the webjob name in the portal
  ZIP_FILE: 'WebJobConsoleApp.zip'
  ZIP_PATH: './output'
  ZIP_FILEPATH: './output/WebJobConsoleApp.zip'
  NUGET_VERSION: '4.6.1'
  AZURE_WEBAPP_PACKAGE_PATH: 'published'
  AZURE_WEBAPP_NAME: 'WebAppForWebJobConsoleApp'
  
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main,processbranch ]
  pull_request:
    branches: [ main,processbranch ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - uses: actions/checkout@v2

     - name: Setup .NET Core
       uses: actions/setup-dotnet@v1
       with:
        dotnet-version: 3.1.101

     - name: Install dependencies
       run: dotnet restore ./WebJobConsoleApp/
       
     - name: Install Nuget
       uses: nuget/setup-nuget@v1
       with:
        nuget-version: ${{ env.NUGET_VERSION}}
        
     - name: NuGet to restore dependencies as well as project-specific tools that are specified in the project file
       run: nuget restore ./WebJobConsoleApp/

     #- name: Build
       #run: dotnet build ./WebJobConsoleApp/ --configuration Release --no-restore 
     
     - name: Setup MSBuild path
       uses: microsoft/setup-msbuild@v1.0.2
       
     - name: Build Solution
       run: msbuild ./WebJobConsoleApp/WebJobConsoleApp/WebJobConsoleApp.csproj /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="\published\"
         
  deploy:
          runs-on: windows-latest
          needs: build
          
          steps:
          - name: Azure Deploy
            uses: azure/webapps-deploy@v1
            with:
              app-name: ${{ env.AZURE_WEBAPP_NAME }}
              publish-profile: ${{ secrets.WEBJOB_PUBLISH_PROFILE_TEST }}
              package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          
          - name: Upload Artifact
            uses : actions/upload-artifact@v1.0.0
            with : 
              name: ${{ env.AZURE_WEBAPP_NAME }}
              path: \published\
               
            
             
