# This is a basic workflow to help you get started with Actions

name: CI

env:
  BINARIES: './output/app_data/jobs/continuous/WebJobForAppManual' # the last folder name will become the webjob name in the portal
  ZIP_FILE: 'WebJobConsoleApp.zip'
  ZIP_PATH: './output'
  ZIP_FILEPATH: './output/WebJobConsoleApp.zip'
  NUGET_VERSION: '4.6.1'
  AZURE_WEBAPP_PACKAGE_PATH: 'published'
  AZURE_WEBAPP_NAME: 'WebAppForWebJobConsoleApp'
  
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main,processbranch ]
  pull_request:
    branches: [ main,processbranch ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - uses: actions/checkout@v2

     - name: Setup .NET Core
       uses: actions/setup-dotnet@v1
       with:
        dotnet-version: 3.1.101
        
     - name: Install dependencies
       run: dotnet restore ./WebJobConsoleApp/
       
     - name: Install Nuget
       uses: nuget/setup-nuget@v1
       with:
        nuget-version: ${{ env.NUGET_VERSION}}
        
     - name: NuGet to restore dependencies as well as project-specific tools that are specified in the project file
       run: nuget restore ./WebJobConsoleApp/

     - name: Build
       run: dotnet build ./WebJobConsoleApp/ --configuration Release
       
     #- name: dotnet publish
      # run: |
      #  dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

     - name: Setup MSBuild path
       uses: microsoft/setup-msbuild@v1.0.2
       
     - name: Build Solution
       run: msbuild.exe ./WebJobConsoleApp/WebJobConsoleApp/WebJobConsoleApp.csproj /nologo /verbosity:m /t:Build /p:_PackageTempDir=${{env.DOTNET_ROOT}}
       
     - name: Upload artifact for deployment job
       uses: actions/upload-artifact@v2
       with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}
         
  deploy:
          runs-on: windows-latest
          needs: build            
          environment:
           name: 'Production'
           url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

          steps:
          - name: Download artifact from build job
            uses: actions/download-artifact@v2
            with:
             name: .net-app

          - name: Deploy to Azure Web App
            id: deploy-to-webapp
            uses: azure/webapps-deploy@v2
            with:
             app-name: 'WebAppForWebJobConsoleApp'
             slot-name: 'Production'
             publish-profile: ${{ secrets.WEBJOB_PUBLISH_PROFILE_TEST }}
             package: .
            
             
